In [79]:
import numpy as np

In [80]:
arr = np.array([(1,2,3,4),(4,5,6,7),(8,9,10,11),(12,13,14,15)])

In [81]:
arr

array([[ 1,  2,  3,  4],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [82]:
arr[1][2]

6

In [83]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [84]:
np.linspace(1,10,10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [85]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [86]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [87]:
np.full((4,4),6)

array([[6, 6, 6, 6],
       [6, 6, 6, 6],
       [6, 6, 6, 6],
       [6, 6, 6, 6]])

In [88]:
np.empty((3,3))

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [89]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [90]:
np.random.randint(0,10,(2,2))

array([[0, 9],
       [5, 7]])

In [91]:
np.random.random((2,2))

array([[0.08692865, 0.70063549],
       [0.03028697, 0.73655175]])

In [92]:
arr

array([[ 1,  2,  3,  4],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [93]:
arr[::2,::2]

array([[ 1,  3],
       [ 8, 10]])

In [94]:
arr1 = np.array([[1,2],[3,4]])
arr2 = np.array([[1,2],[3,4]])

In [95]:
arr3 = arr1+arr2

In [96]:
arr3

array([[2, 4],
       [6, 8]])

In [97]:
arr1 = np.array(((1,2),(3,4)))
arr2 = np.array(((1,2),(3,4)))

In [98]:
arr1[1][0] = arr2[0][0]

In [99]:
arr1

array([[1, 2],
       [1, 4]])

In [100]:
arr

array([[ 1,  2,  3,  4],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [101]:
arr.any()

True

In [102]:
arr.all()

True

In [103]:
arr[1][1] = 0

In [104]:
arr.any()

True

In [105]:
arr.all()

False

In [106]:
arr4 = np.zeros((2,2))

In [107]:
arr4.any()

False

In [108]:
arr4.mean()

0.0

In [109]:
arr3.mean()

5.0

In [110]:
arr3.sum()

20

In [111]:
arr3.cumsum()

array([ 2,  6, 12, 20])

In [112]:
arr3

array([[2, 4],
       [6, 8]])

In [113]:
arr3.cumprod()

array([  2,   8,  48, 384])

In [114]:
arr3.real

array([[2, 4],
       [6, 8]])

In [115]:
arr3.imag

array([[0, 0],
       [0, 0]])

In [116]:
arr5 = np.arange(16).reshape((4,4))

In [117]:
arr5.reshape(-4,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [118]:
arr5.reshape(-1,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [119]:
arr6 = np.array([12,34],ndmin = 6)

In [120]:
arr6

array([[[[[[12, 34]]]]]])

In [121]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

In [122]:
arr[1][1]

7

In [123]:
arr[1,1]

7

In [124]:
arr[1,-1]

10

In [125]:
arr.dtype

dtype('int32')

In [126]:
arr7 = np.arange(2,10,2)

In [127]:
arr7

array([2, 4, 6, 8])

In [128]:
np.linspace(2,10,6)

array([ 2. ,  3.6,  5.2,  6.8,  8.4, 10. ])

In [129]:
arr8 = np.empty((2,2))

In [130]:
arr8

array([[0., 0.],
       [0., 0.]])

In [132]:
arr9 = np.empty((3,3))

In [133]:
arr9

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [134]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [135]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [139]:
np.diag([1,2,3,4,4,3])

array([[1, 0, 0, 0, 0, 0],
       [0, 2, 0, 0, 0, 0],
       [0, 0, 3, 0, 0, 0],
       [0, 0, 0, 4, 0, 0],
       [0, 0, 0, 0, 4, 0],
       [0, 0, 0, 0, 0, 3]])

In [142]:
np.random.random(10)

array([0.62769199, 0.64034732, 0.90945288, 0.02223134, 0.64909859,
       0.66457321, 0.72388943, 0.84045495, 0.72691934, 0.12961756])

In [149]:
np.random.randint(1)

0

In [151]:
a2 = np.array([[1,2],[0,2]])

In [152]:
a2.any()

True

In [153]:
a2.sum()

5

In [154]:
a2.cumsum()

array([1, 3, 3, 5])