In [1]:
import numpy as np

In [24]:
print("1d array",np.array([1,2,3,4]))

1d array [1 2 3 4]


In [25]:
print("Range of values - method -1 ",np.arange(10))

Range of values - method -1  [0 1 2 3 4 5 6 7 8 9]


In [26]:
print("Range of values - method -1 ",np.arange(0,10,2))

Range of values - method -1  [0 2 4 6 8]


In [27]:
print("Range of values - method -1 ",np.arange(10,0,-2))

Range of values - method -1  [10  8  6  4  2]


In [28]:
print(np.version)

<module 'numpy.version' from 'C:\\Users\\suman\\anaconda3\\lib\\site-packages\\numpy\\version.py'>


In [29]:
arr = np.array([1,2,3,4,5])

In [30]:
type(arr)

numpy.ndarray

In [31]:
print(type(arr))

<class 'numpy.ndarray'>


In [32]:
arr = np.array(42)

In [33]:
print(arr)

42


In [34]:
arr = np.array([[1,2,3,4],[1,2,3,4]])

In [35]:
print(arr)

[[1 2 3 4]
 [1 2 3 4]]


In [36]:
print("array using linear space",np.linspace(0,1,5))

array using linear space [0.   0.25 0.5  0.75 1.  ]


In [37]:
print("array using linear space",np.linspace(0,2,5))

array using linear space [0.  0.5 1.  1.5 2. ]


In [38]:
print("3 D array ",np.array([[1,2],[3,4],[5,6],[7,8]]))

3 D array  [[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [39]:
print("zero initialized : ",np.zeros([2,2]))

zero initialized :  [[0. 0.]
 [0. 0.]]


In [40]:
print("zero initialized : ",np.zeros((4,2,3)))

zero initialized :  [[[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]]


In [41]:
print("One initialized : ",np.ones((3,2,5)))

One initialized :  [[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]


In [42]:
print("Specific number initialized : ",np.full((2,2),5))

Specific number initialized :  [[5 5]
 [5 5]]


In [43]:
arr = np.array((1,2,3,4,5),ndmin = 5)

In [44]:
print(arr.ndim)

5


In [45]:
print(arr)

[[[[[1 2 3 4 5]]]]]


In [47]:
arr2 = np.array(((1,2,3,4,),(1,2,3,4)))

In [48]:
print(arr2.ndivm)

2


In [76]:
print("Specific number initilized",np.full((2,3),5))

Specific number initilized [[5 5 5]
 [5 5 5]]


In [77]:
print("Idientity Matirx array \n",np.eye(3,4))

Idientity Matirx array 
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]


In [79]:
print("Uninitilized array \n",np.empty((4,3)))

Uninitilized array 
 [[1. 0. 0.]
 [0. 0. 1.]
 [0. 0. 0.]
 [0. 1. 0.]]


In [59]:
print("Diagonal elements array \n",np.diag([1,2,3,4]))

Diagonal elements array 
 [[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


In [63]:
print("Random number array \n ",np.random.random((2,2)))

Random number array 
  [[0.26841688 0.21069247]
 [0.65763799 0.22623962]]


In [65]:
print(arr2.shape)#for checking the size of the array

(2, 4)


In [66]:
print(arr2.size)

8


In [74]:
print("Random arra with elements in specifi range \n ",np.random.randint(0,10,(2,2)))

Random arra with elements in specifi range 
  [[4 9]
 [7 2]]


In [75]:
print(np.random.randint(0,10))

9


In [88]:
A1 = np.array(([1,2],[3,4]))
print(A1[1][1])
print(A1[1,1])

4
4


In [89]:
a = (4)
print(a)

4


In [90]:
a = (4,)
print(a)

(4,)


In [94]:
print(arr2[1:])

[1 2 3 4]


In [98]:
arr3 = np.array([[1,32,34,51],[1,31,41,51],[1415,115,1,51],[1,15,1,1]])

In [99]:
print(arr3[1])

[ 1 31 41 51]


In [100]:
print(arr3[2])

[1415  115    1   51]


In [101]:
print(arr3[-1])

[ 1 15  1  1]


In [102]:
print(arr3[-3:-1])

[[   1   31   41   51]
 [1415  115    1   51]]


In [103]:
print(arr3[1:-1])

[[   1   31   41   51]
 [1415  115    1   51]]


In [104]:
print(arr3[::])

[[   1   32   34   51]
 [   1   31   41   51]
 [1415  115    1   51]
 [   1   15    1    1]]


In [105]:
print(arr3[::2])

[[   1   32   34   51]
 [1415  115    1   51]]


In [106]:
print(arr3[2::-1])

[[1415  115    1   51]
 [   1   31   41   51]
 [   1   32   34   51]]


In [108]:
print(arr3[1:-3:1])

[]


In [109]:
print(arr3[2:4:1])

[[1415  115    1   51]
 [   1   15    1    1]]


In [111]:
print(np.full([2,2],5))

[[5 5]
 [5 5]]


In [112]:
print(np.arange(10))

[0 1 2 3 4 5 6 7 8 9]


In [116]:
print(np.arange(0,100,10))

[ 0 10 20 30 40 50 60 70 80 90]


In [117]:
arr4 = np.array([[2,3,4,3,6],[1,2,5,7,5],[3,4,3,3,5],[5,6,3,2,1],[3,1,4,5,6]])

In [118]:
print(arr4[1:3,1:])

[[2 5 7 5]
 [4 3 3 5]]


In [119]:
print(arr4[:,1])

[3 2 4 6 1]


In [120]:
print(arr4[:2,1])

[3 2]


In [121]:
print(arr4[::2,1])

[3 4 1]


In [123]:
print(arr4[::-1])

[[3 1 4 5 6]
 [5 6 3 2 1]
 [3 4 3 3 5]
 [1 2 5 7 5]
 [2 3 4 3 6]]


In [125]:
arr4[:,1]

array([3, 2, 4, 6, 1])

[[2 3 4 3 6]
 [1 2 5 7 5]
 [3 4 3 3 5]
 [5 6 3 2 1]
 [3 1 4 5 6]]
